---
- name: refresh apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: is_ubuntu_derivative
  become: true

- name: install build utilities
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ curl_package_name }}"
    - "{{ rsync_package_name }}"
    - "{{ ssh_package_name }}"
  become: true

# install python required packages on trusty
- name: install python SSL support packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - python-dev
    - python-openssl
    - python-pip
    - python-pyasn1
    - python-urllib3
  when: is_ubuntu_trusty_derivative
  become: true

- name: install ndg-httpsclient pip module
  pip: name=ndg-httpsclient state=present
  when: is_ubuntu_trusty_derivative
  become: true
