---
- name: install git
  package: name=git state=present
  become: true

- name: install curl
  package: name=curl state=present
  become: true

- name: install rsync
  package: name=rsync state=present
  become: true

- name: install ssh client
  package:
    name: "{{ ssh_package_name }}"
    state: present
  become: true

- name: install c compiler
  package: name=gcc state=present
  become: true

- name: install musl packages
  package:
    name: "{{ item }}"
    state: present
  when: rust_dev_include_musl and is_ubuntu_derivative
  become: true
  loop:
    - musl
    - musl-dev
    - musl-tools

- name: install additional system packages
  package:
    name: "{{ rust_addtl_system_packages }}"
    state: present
  become: true
