---
- name: establish operating system
  set_fact:
    os_name: |-
      {% if ansible_distribution|lower in ("redhat", "centos") -%}
        redhat
      {%- else -%}
        {{ ansible_distribution|lower }}
      {%- endif %}
- name: establish operating system release
  set_fact:
    os_release: |-
      {% if os_name == "redhat" -%}
        rhel{{ ansible_distribution_major_version }}
      {%- else -%}
        {{ ansible_distribution_release | lower }}
      {%- endif %}
